version: '3'

services:
  wordpress:
    build:
      context: php
    ports:
      - '80:80'
      - '443:443'
    networks:
      - webnet
    volumes:
      - ./vol/wordpress:/var/www/html
      - ../build:/var/www/html/wp-content/plugins/wp-discord-poster-bot
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASS: toor
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PREFIX: wppre_
      WORDPRESS_INSTALL_URL: 'https://localhost'
      WORDPRESS_INSTALL_TITLE: 'Test WordPress Site'
      WORDPRESS_INSTALL_ADMIN_USER: admin
      WORDPRESS_INSTALL_ADMIN_EMAIL: admin@example.com
      WORDPRESS_INSTALL_ADMIN_PASS: nimda
      WORDPRESS_CFG_WP_DEBUG: 1
      WORDPRESS_CFG_DEBUG_LOG: 1
      WORDPRESS_CFG_SCRIPT_DEBUG: 1
      WORDPRESS_CFG_AUTOMATIC_UPDATER_DISABLED: 1

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    networks:
      - webnet
    volumes:
      - ./vol/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor

networks:
  webnet:
